	class l129_blk;
	class l129_blk_bcsewpn:	  l129_blk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class l129_tan;
	class l129_tan_bcsewpn:	  l129_tan{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_kmod_mlok;	
	class ar10_kmod_mlok_bcsewpn:	  ar10_kmod_mlok{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_pof;	
	class ar10_pof_bcsewpn:	  ar10_pof{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class sig716_01;	
	class sig716_01_bcsewpn:	  sig716_01{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class sig716_02;	
	class sig716_02_bcsewpn:	  sig716_02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_mlok;	
	class ar10_mlok_bcsewpn:	  ar10_mlok{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_mlok_tan;	
	class ar10_mlok_tan_bcsewpn:	  ar10_mlok_tan{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_ar10_pts;	
	class kt_ar10_pts_bcsewpn:	  kt_ar10_pts{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_sr25ecc;	
	class kt_sr25ecc_bcsewpn:	  kt_sr25ecc{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class l129_blk_65;	
	class l129_blk_65_bcsewpn:	  l129_blk_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class l129_tan_65;	
	class l129_tan_65_bcsewpn:	  l129_tan_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_kmod_mlok_65;	
	class ar10_kmod_mlok_65_bcsewpn:	  ar10_kmod_mlok_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_pof_65;	
	class ar10_pof_65_bcsewpn:	  ar10_pof_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class sig716_01_65;	
	class sig716_01_65_bcsewpn:	  sig716_01_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class sig716_02_65;	
	class sig716_02_65_bcsewpn:	  sig716_02_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_mlok_65;	
	class ar10_mlok_65_bcsewpn:	  ar10_mlok_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_mlok_tan_65;	
	class ar10_mlok_tan_65_bcsewpn:	  ar10_mlok_tan_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_ar10_pts_65;	
	class kt_ar10_pts_65_bcsewpn:	  kt_ar10_pts_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_sr25ecc_65;	
	class kt_sr25ecc_65_bcsewpn:	  kt_sr25ecc_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_M110A1_blk02;	
	class kt_M110A1_blk02_bcsewpn:	  kt_M110A1_blk02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\rhsusf\addons\rhsusf_weapons\m4\data\rhs_foregrip_black_co.paa","\kt_m1102\data\rail_ar_mk8_13_blk41.paa","\kt_m1102\data\hu_blk.paa","\A3\Weapons_F_Exp\Rifles\SPAR_03\Data\arifle_SPAR_03_blk_F_01_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_03\Data\arifle_SPAR_03_blk_F_02_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_01\Data\arifle_SPAR_01_blk_F_01_co.paa"};
	};
	class kt_M110A1_ral02;	
	class kt_M110A1_ral02_bcsewpn:	  kt_M110A1_ral02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\kt_m1102\data2\rhs_foregrip_de_co.paa","\kt_m1102\data\rail_ar_mk8_13_ral21.paa","\kt_m1102\data\hu_ral.paa","\kt_m1102\data2\arifle_SPAR_03_01_de.paa","\kt_m1102\data2\arifle_SPAR_03_02_de.paa","\kt_m1102\data2\arifle_SPAR_01_01_de.paa"};
	};
	class kt_M110A1_fde02;	
	class kt_M110A1_fde02_bcsewpn:	  kt_M110A1_fde02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\kt_m1102\data2\rhs_foregrip_de_co.paa","\kt_m1102\data\rail_ar_mk8_13_de21.paa","\kt_m1102\data\hu_de.paa","\kt_m1102\data2\arifle_SPAR_03_01_de.paa","\kt_m1102\data2\arifle_SPAR_03_02_de.paa","\kt_m1102\data2\arifle_SPAR_01_01_de.paa"};
	};
	class kt_M110A1_sand02;	
	class kt_M110A1_sand02_bcsewpn:	  kt_M110A1_sand02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\kt_m1102\data2\rhs_foregrip_sand_co.paa","\kt_m1102\data\rail_ar_mk8_13_sand.paa","\kt_m1102\data\hu_sand.paa","\kt_m1102\data2\arifle_SPAR_03_snd_F_01_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_03\Data\arifle_SPAR_03_snd_F_02_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_01\Data\arifle_SPAR_01_snd_F_01_co.paa"};
	};
	class kt_M110A1_khk02;	
	class kt_M110A1_khk02_bcsewpn:	  kt_M110A1_khk02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\kt_m1102\data2\rhs_foregrip_khk_co.paa","\kt_m1102\data\rail_ar_mk8_13_khk.paa","\kt_m1102\data\hu_khk.paa","\kt_m1102\data2\arifle_SPAR_03_khk_F_01_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_03\Data\arifle_SPAR_03_khk_F_02_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_01\Data\arifle_SPAR_01_khk_F_01_co.paa"};
	};
	class kt_M110A1_blk03;	
	class kt_M110A1_blk03_bcsewpn:	  kt_M110A1_blk03{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\rhsusf\addons\rhsusf_weapons\m4\data\rhs_foregrip_black_co.paa","\kt_m1102\data\rail_ar_mk8_13_blk41.paa","\kt_m1102\data\hu_blk.paa","\A3\Weapons_F_Exp\Rifles\SPAR_03\Data\arifle_SPAR_03_blk_F_01_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_03\Data\arifle_SPAR_03_blk_F_02_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_01\Data\arifle_SPAR_01_blk_F_01_co.paa"};
	};
	class kt_M110A1_ral03;	
	class kt_M110A1_ral03_bcsewpn:	  kt_M110A1_ral03{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\kt_m1102\data2\rhs_foregrip_de_co.paa","\kt_m1102\data\rail_ar_mk8_13_ral21.paa","\kt_m1102\data\hu_ral.paa","\kt_m1102\data2\arifle_SPAR_03_01_de.paa","\kt_m1102\data2\arifle_SPAR_03_02_de.paa","\kt_m1102\data2\arifle_SPAR_01_01_de.paa"};
	};
	class kt_M110A1_fde03;	
	class kt_M110A1_fde03_bcsewpn:	  kt_M110A1_fde03{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\kt_m1102\data2\rhs_foregrip_de_co.paa","\kt_m1102\data\rail_ar_mk8_13_de21.paa","\kt_m1102\data\hu_de.paa","\kt_m1102\data2\arifle_SPAR_03_01_de.paa","\kt_m1102\data2\arifle_SPAR_03_02_de.paa","\kt_m1102\data2\arifle_SPAR_01_01_de.paa"};
	};
	class kt_M110A1_khk03;	
	class kt_M110A1_khk03_bcsewpn:	  kt_M110A1_khk03{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\kt_m1102\data2\rhs_foregrip_sand_co.paa","\kt_m1102\data\rail_ar_mk8_13_sand.paa","\kt_m1102\data\hu_sand.paa","\kt_m1102\data2\arifle_SPAR_03_snd_F_01_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_03\Data\arifle_SPAR_03_snd_F_02_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_01\Data\arifle_SPAR_01_snd_F_01_co.paa"};
	};
	class kt_M110A1_sand03;	
	class kt_M110A1_sand03_bcsewpn:	  kt_M110A1_sand03{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","vfg","humu2","yuan","camo1","camo2","camo3"};
		hiddenSelectionsTextures[] = {"","\kt_m1102\data2\rhs_foregrip_sand_co.paa","\kt_m1102\data\rail_ar_mk8_13_sand.paa","\kt_m1102\data\hu_sand.paa","\kt_m1102\data2\arifle_SPAR_03_snd_F_01_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_03\Data\arifle_SPAR_03_snd_F_02_co.paa","\A3\Weapons_F_Exp\Rifles\SPAR_01\Data\arifle_SPAR_01_snd_F_01_co.paa"};
	};
	class kt_MK20_SSR;	
	class kt_MK20_SSR_bcsewpn:	  kt_MK20_SSR{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_MK20_SSR_blk;	
	class kt_MK20_SSR_blk_bcsewpn:	  kt_MK20_SSR_blk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_MK20_SSR_65creedmoor;	
	class kt_MK20_SSR_65creedmoor_bcsewpn:	  kt_MK20_SSR_65creedmoor{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_MK20_SSR_65creedmoorblk;	
	class kt_MK20_SSR_65creedmoorblk_bcsewpn:	  kt_MK20_SSR_65creedmoorblk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_SCAR_PR;	
	class kt_SCAR_PR_bcsewpn:	  kt_SCAR_PR{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_SCAR_PR_BLK;	
	class kt_SCAR_PR_BLK_bcsewpn:	  kt_SCAR_PR_BLK {
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_SCARPR_65;	
	class kt_SCARPR_65_bcsewpn:	  kt_SCARPR_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_SCARPR_65blk;	
	class kt_SCARPR_65blk_bcsewpn:	  kt_SCARPR_65blk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_338nm;	
	class kt_mrad_338nm_bcsewpn:	  kt_mrad_338nm{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_338lm;	
	class kt_mrad_338lm_bcsewpn:	  kt_mrad_338lm{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_762nato;	
	class kt_mrad_762nato_bcsewpn:	  kt_mrad_762nato{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_300wm;	
	class kt_mrad_300wm_bcsewpn:	  kt_mrad_300wm{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_65Creedmoor;	
	class kt_mrad_65Creedmoor_bcsewpn:	  kt_mrad_65Creedmoor{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_338nm2;	
	class kt_mrad_338nm2_bcsewpn:	  kt_mrad_338nm2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_338lm2;	
	class kt_mrad_338lm2_bcsewpn:	  kt_mrad_338lm2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_762nato2;	
	class kt_mrad_762nato2_bcsewpn:	  kt_mrad_762nato2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_300wm2;	
	class kt_mrad_300wm2_bcsewpn:	  kt_mrad_300wm2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mrad_65Creedmoor2;	
	class kt_mrad_65Creedmoor2_bcsewpn:	  kt_mrad_65Creedmoor2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
		
		
	class cadex50;
	class cadex50_02;
	class ax50;
	class ax50_tan2;
	class ax50_blk;
	class kt_tac50;
	class kt_tac50_02;
	class kt_tac50_03;
	class kt_tac50_04;
	class kt_tac50_05;
	class kt_tac50_08;
	class kt_tac50_051;
	class kt_tac50_081;
	class kt_tac50_06;
	class kt_tac50_07;
	class axmc;
	class axmc_65;
	class ax50_tan;
	class t5000;
	class t5000_bolt2;
	class cadex50_bolt2;
	class cadex50_02_bolt2;
	class ax50_bolt2;
	class ax50_tan2_bolt2;
	class ax50_blk_bolt2;
	class kt_tac50_bolt2;
	class kt_tac50_02_bolt2;
	class kt_tac50_03_bolt2;
	class kt_tac50_04_bolt2;
	class kt_tac50_05_bolt2;
	class kt_tac50_08_bolt2;
	class kt_tac50_051_bolt2;
	class kt_tac50_081_bolt2;
	class kt_tac50_06_bolt2;
	class kt_tac50_07_bolt2;
	class axmc_bolt2;
	class axmc_65_bolt2;
	class ax50_tan_bolt2;
	
	
	class cadex50_bcsewpn: cadex50{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class cadex50_02_bcsewpn: cadex50_02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ax50_bcsewpn: ax50{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ax50_tan2_bcsewpn: ax50_tan2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","all","bolt2"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\ax50_tan2\ax50_tan.paa",""};
	};
	class ax50_blk_bcsewpn: ax50_blk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_tac50_bcsewpn: kt_tac50{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_tac50_02_bcsewpn: kt_tac50_02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_tac50_03_bcsewpn: kt_tac50_03{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_tac50_04_bcsewpn: kt_tac50_04
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\21.paa"};
	};
	class kt_tac50_05_bcsewpn: kt_tac50_05
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\21_tan.paa"};
	};
	class kt_tac50_08_bcsewpn: kt_tac50_08
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\211_tan.paa"};
	};
	class kt_tac50_051_bcsewpn: kt_tac50_051
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\21_tan.paa"};
	};
	class kt_tac50_081_bcsewpn: kt_tac50_081
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\211_tan.paa"};
	};
	class kt_tac50_06_bcsewpn: kt_tac50_06
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\21_olive.paa"};
	};
	class kt_tac50_07_bcsewpn: kt_tac50_07
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\21_khk.paa"};
	};
	class axmc_bcsewpn: axmc{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class axmc_65_bcsewpn: axmc_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ax50_tan_bcsewpn: ax50_tan{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class t5000_bcsewpn: t5000{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class cadex50_bolt2_bcsewpn: cadex50_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class cadex50_02_bolt2_bcsewpn: cadex50_02_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ax50_bolt2_bcsewpn: ax50_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ax50_tan2_bolt2_bcsewpn: ax50_tan2_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ax50_blk_bolt2_bcsewpn: ax50_blk_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_tac50_bolt2_bcsewpn: kt_tac50_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_tac50_02_bolt2_bcsewpn: kt_tac50_02_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_tac50_03_bolt2_bcsewpn: kt_tac50_03_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_tac50_04_bolt2_bcsewpn: kt_tac50_04_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_tac50_05_bolt2_bcsewpn: kt_tac50_05_bolt2
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\21_tan.paa"};
	};
	class kt_tac50_08_bolt2_bcsewpn: kt_tac50_08_bolt2
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\211_tan.paa"};
	};
	class kt_tac50_051_bolt2_bcsewpn: kt_tac50_051_bolt2
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\21_tan.paa"};
	};
	class kt_tac50_081_bolt2_bcsewpn: kt_tac50_081_bolt2
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\211_tan.paa"};
	};
	class kt_tac50_06_bolt2_bcsewpn: kt_tac50_06_bolt2
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\21_olive.paa"};
	};
	class kt_tac50_07_bolt2_bcsewpn: kt_tac50_07_bolt2
		{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\tac50\21_khk.paa"};
	};
	class axmc_bolt2_bcsewpn: axmc_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class axmc_65_bolt2_bcsewpn: axmc_65_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ax50_tan_bolt2_bcsewpn: ax50_tan_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class t5000_bolt2_bcsewpn: t5000_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto_bcsewpn:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL_bcsewpn: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};


	class KT_tac338;	
	class KT_tac338_bcsewpn:	  KT_tac338{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class r93_lrs2;	
	class r93_lrs2_bcsewpn:  r93_lrs2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	
	class r93_lrs2_2;	
	class r93_lrs2_2_bcsewpn:  r93_lrs2_2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	
	class kt_obr556;	
	class kt_obr556_bcsewpn:	 kt_obr556{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_obr556_grip_bcsewpn: kt_obr556_bcsewpn{};	
	class kt_obr556_grip2_bcsewpn: kt_obr556_bcsewpn{};	
	class kt_obr556_grip3_bcsewpn: kt_obr556_bcsewpn{};	

	class kt_obr556_c;	
	class kt_obr556_c_bcsewpn:	 kt_obr556_c{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_obr556_c_grip_bcsewpn: kt_obr556_c_bcsewpn{};	
	class kt_obr556_c_grip2_bcsewpn: kt_obr556_c_bcsewpn{};	
	class kt_obr556_c_grip3_bcsewpn: kt_obr556_c_bcsewpn{};	
	class kt_obr556_r;	
	class kt_obr556_r_bcsewpn:	 kt_obr556_r{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_obr556_r_grip_bcsewpn: kt_obr556_r_bcsewpn{};	
	class kt_obr556_r_grip2_bcsewpn: kt_obr556_r_bcsewpn{};	
	class kt_obr556_r_grip3_bcsewpn: kt_obr556_r_bcsewpn{};	
	class kt_obr762;	
	class kt_obr762_bcsewpn:	 kt_obr762{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_obr762_grip_bcsewpn: kt_obr762_bcsewpn{};	
	class kt_obr762_grip2_bcsewpn: kt_obr762_bcsewpn{};	
	class kt_obr762_grip3_bcsewpn: kt_obr762_bcsewpn{};	
	class kt_obr762_02;	
	class kt_obr762_02_bcsewpn:	 kt_obr762_02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_obr762_02_grip_bcsewpn: kt_obr762_02_bcsewpn{};	
	class kt_obr762_02_grip2_bcsewpn: kt_obr762_02_bcsewpn{};	
	class kt_obr762_02_grip3_bcsewpn: kt_obr762_02_bcsewpn{};	
	class ar15_sig516;	
	class ar15_sig516_bcsewpn:	 ar15_sig516{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar15_sig516_grip_bcsewpn: ar15_sig516_bcsewpn{};	
	class ar15_sig516_grip2_bcsewpn: ar15_sig516_bcsewpn{};	
	class ar15_sig516_grip3_bcsewpn: ar15_sig516_bcsewpn{};	
	class ar15_mlok;	
	class ar15_mlok_bcsewpn:	 ar15_mlok{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","all"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\mlok\mlok.paa"};
	};
	class ar15_mlok_grip_bcsewpn: ar15_mlok_bcsewpn{};	
	class ar15_mlok_grip2_bcsewpn: ar15_mlok_bcsewpn{};	
	class ar15_mlok_grip3_bcsewpn: ar15_mlok_bcsewpn{};
	class ar15_mlok_blk;	
	class ar15_mlok_blk_bcsewpn:	 ar15_mlok_blk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","all"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\mlok\mlok_02.paa"};
	};
	class ar15_mlok_blk_grip_bcsewpn: ar15_mlok_blk_bcsewpn{};	
	class ar15_mlok_blk_grip2_bcsewpn: ar15_mlok_blk_bcsewpn{};	
	class ar15_mlok_blk_grip3_bcsewpn: ar15_mlok_blk_bcsewpn{};	
	class ar15_urgi_cqc;	
	class ar15_urgi_cqc_bcsewpn:	 ar15_urgi_cqc{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar15_urgi_cqc_grip_bcsewpn: ar15_urgi_cqc_bcsewpn{};	
	class ar15_urgi_cqc_grip2_bcsewpn: ar15_urgi_cqc_bcsewpn{};	
	class ar15_urgi_cqc_grip3_bcsewpn: ar15_urgi_cqc_bcsewpn{};	
	class ar15_urgi_std;	
	class ar15_urgi_std_bcsewpn:	 ar15_urgi_std{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar15_urgi_std_grip_bcsewpn: ar15_urgi_std_bcsewpn{};	
	class ar15_urgi_std_grip2_bcsewpn: ar15_urgi_std_bcsewpn{};	
	class ar15_urgi_std_grip3_bcsewpn: ar15_urgi_std_bcsewpn{};	
	class ar15_urgi_ctr;	
	class ar15_urgi_ctr_bcsewpn:	 ar15_urgi_ctr{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar15_urgi_ctr_grip_bcsewpn: ar15_urgi_ctr_bcsewpn{};	
	class ar15_urgi_ctr_grip2_bcsewpn: ar15_urgi_ctr_bcsewpn{};	
	class ar15_urgi_ctr_grip3_bcsewpn: ar15_urgi_ctr_bcsewpn{};	
	class ar15_urgi_lb;	
	class ar15_urgi_lb_bcsewpn:	 ar15_urgi_lb{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar15_urgi_lb_grip_bcsewpn: ar15_urgi_lb_bcsewpn{};	
	class ar15_urgi_lb_grip2_bcsewpn: ar15_urgi_lb_bcsewpn{};	
	class ar15_urgi_lb_grip3_bcsewpn: ar15_urgi_lb_bcsewpn{};	
	class ar15_urgi_ctrgl;	
	class ar15_urgi_ctrgl_bcsewpn:	 ar15_urgi_ctrgl{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo3","urgigl2"};
		hiddenSelectionsTextures[] = {"","",""};
	};
	class ar15_urgi_ctrgl_grip_bcsewpn: ar15_urgi_ctrgl_bcsewpn{};	
	class ar15_urgi_ctrgl_grip2_bcsewpn: ar15_urgi_ctrgl_bcsewpn{};	
	class ar15_urgi_ctrgl_grip3_bcsewpn: ar15_urgi_ctrgl_bcsewpn{};	
	class ar15_urgi_ctrgl02;	
	class ar15_urgi_ctrgl02_bcsewpn:	 ar15_urgi_ctrgl02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","gl01","gl02","13b","camo3"};
		hiddenSelectionsTextures[] = {"","kt_ar15\data2\urgi\eglm_co_tan2.paa","kt_ar15\data2\mk13\mk13_co.paa","",""};
	};
	class ar15_urgi_ctrgl02_grip_bcsewpn: ar15_urgi_ctrgl02_bcsewpn{};	
	class ar15_urgi_ctrgl02_grip2_bcsewpn: ar15_urgi_ctrgl02_bcsewpn{};	
	class ar15_urgi_ctrgl02_grip3_bcsewpn: ar15_urgi_ctrgl02_bcsewpn{};	
	class ar15_urgi_ctr_blkgl;	
	class ar15_urgi_ctr_blkgl_bcsewpn:	 ar15_urgi_ctr_blkgl{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","urgictr","ctr","gl01","gl02","13b","camo3","urgigl2"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\urgi\one_02.paa","\kt_ar15\data2\ctr\ctr_blk.paa","\kt_ar15\data2\urgi\eglm_co_black.paa","\kt_ar15\data2\urgi\eglm_co_black.paa","\kt_ar15\data3\13b2.paa","",""};
	};
	class ar15_urgi_cqcgl;	
	class ar15_urgi_cqcgl_bcsewpn:	 ar15_urgi_cqcgl{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar15_kmod_mlok;	
	class ar15_kmod_mlok_bcsewpn:	 ar15_kmod_mlok{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar15_kmod_mlok_grip_bcsewpn: ar15_kmod_mlok_bcsewpn{};	
	class ar15_kmod_mlok_grip2_bcsewpn: ar15_kmod_mlok_bcsewpn{};	
	class ar15_kmod_mlok_grip3_bcsewpn: ar15_kmod_mlok_bcsewpn{};	
	class ar15_kmod_mlok_blk;	
	class ar15_kmod_mlok_blk_bcsewpn:	 ar15_kmod_mlok_blk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar15_kmod_mlok_blk_grip_bcsewpn: ar15_kmod_mlok_blk_bcsewpn{};	
	class ar15_kmod_mlok_blk_grip2_bcsewpn: ar15_kmod_mlok_blk_bcsewpn{};	
	class ar15_kmod_mlok_blk_grip3_bcsewpn: ar15_kmod_mlok_blk_bcsewpn{};	
	class kt_ar15;	
	class kt_ar15_bcsewpn:	 kt_ar15{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_ar15_grip_bcsewpn: kt_ar15_bcsewpn{};	
	class kt_ar15_grip2_bcsewpn: kt_ar15_bcsewpn{};	
	class kt_ar15_grip3_bcsewpn: kt_ar15_bcsewpn{};	
	class kt_ar15_mlok;	
	class kt_ar15_mlok_bcsewpn:	 kt_ar15_mlok{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_ar15_mlok_grip_bcsewpn: kt_ar15_mlok_bcsewpn{};	
	class kt_ar15_mlok_grip2_bcsewpn: kt_ar15_mlok_bcsewpn{};	
	class kt_ar15_mlok_grip3_bcsewpn: kt_ar15_mlok_bcsewpn{};	
	class kt_ar15_mlok01;	
	class kt_ar15_mlok01_bcsewpn:	 kt_ar15_mlok01{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_ar15_mlok01_grip_bcsewpn: kt_ar15_mlok01_bcsewpn{};	
	class kt_ar15_mlok01_grip2_bcsewpn: kt_ar15_mlok01_bcsewpn{};	
	class kt_ar15_mlok01_grip3_bcsewpn: kt_ar15_mlok01_bcsewpn{};	
	class kt_AR15_gilboa;	
	class kt_AR15_gilboa_bcsewpn:	 kt_AR15_gilboa{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_AR15_gilboa_grip_bcsewpn: kt_AR15_gilboa_bcsewpn{};	
	class kt_AR15_gilboa_grip2_bcsewpn: kt_AR15_gilboa_bcsewpn{};	
	class kt_AR15_gilboa_grip3_bcsewpn: kt_AR15_gilboa_bcsewpn{};	
	class kt_ar15_50;	
	class kt_ar15_50_bcsewpn: kt_ar15_50{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_ar15_50_grip_bcsewpn: kt_ar15_50_bcsewpn{};	
	class kt_ar15_50_grip2_bcsewpn: kt_ar15_50_bcsewpn{};	
	class kt_ar15_50_grip3_bcsewpn: kt_ar15_50_bcsewpn{};	
	class kt_mk16pdw;
	class kt_mk16pdw_bcsewpn: kt_mk16pdw
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_SCAR_SC_blk;
	class kt_SCAR_SC_blk_bcsewpn: kt_SCAR_SC_blk
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_SCAR_SC_300;
	class kt_SCAR_SC_300_bcsewpn: kt_SCAR_SC_300
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	
	class kt_axmcasr_grey;
	class kt_axmcasr_blk1;
	class kt_axmcasr_blk2;
	class kt_axmcasr_tan;
	class kt_axmcasr_skin2;
	class kt_axmcasr_skin3;
	class kt_axmcasr_skin4;
	class kt_axmcasr_skin5;
	class kt_axmcasr_grey_bolt2;
	class kt_axmcasr_blk1_bolt2;
	class kt_axmcasr_blk2_bolt2;
	class kt_axmcasr_tan_bolt2;
	class kt_axmcasr_skin2_bolt2;
	class kt_axmcasr_skin3_bolt2;
	class kt_axmcasr_skin4_bolt2;
	class kt_axmcasr_skin5_bolt2;
	
	class kt_axmcasr_grey_bcsewpn: kt_axmcasr_grey
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt2","hu"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_blk.paa","\kt_axmcasr\data\butt_blk.paa","","\kt_axmcasr\data\rifle_blk.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_blk1_bcsewpn: kt_axmcasr_blk1
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt2","hu"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_blk2.paa","\kt_axmcasr\data\butt_blk2.paa","","\kt_axmcasr\data\hu.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_blk2_bcsewpn: kt_axmcasr_blk2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt2""\kt_axmcasr\data2\rifle1.rvmat"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_blk2.paa","\kt_axmcasr\data\butt_blk2.paa","","\kt_axmcasr\data\hu.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle14.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle14.rvmat"};
	};
	class kt_axmcasr_tan_bcsewpn: kt_axmcasr_tan
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt2","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_tan.paa","\kt_axmcasr\data\butt_tan.paa","","\kt_axmcasr\data\rifle_tan.paa","\kt_axmcasr\data\rifle_tan.paa","\kt_axmcasr\data\rifle_tan.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_skin2_bcsewpn: kt_axmcasr_skin2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt2","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_skin2.paa","\kt_axmcasr\data\butt_skin2.paa","","\kt_axmcasr\data\rifle_skin2.paa","\kt_axmcasr\data\rifle_skin2.paa","\kt_axmcasr\data\rifle_skin2.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_skin3_bcsewpn: kt_axmcasr_skin3
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt2","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_skin3.paa","\kt_axmcasr\data\butt_skin3.paa","","\kt_axmcasr\data\rifle_skin3.paa","\kt_axmcasr\data\rifle_skin3.paa","\kt_axmcasr\data\rifle_skin3.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_skin4_bcsewpn: kt_axmcasr_skin4
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt2","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_skin4.paa","\kt_axmcasr\data\butt_skin4.paa","","\kt_axmcasr\data\rifle_skin4.paa","\kt_axmcasr\data\rifle_skin4.paa","\kt_axmcasr\data\rifle_skin4.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_skin5_bcsewpn: kt_axmcasr_skin5
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt2","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_skin5.paa","\kt_axmcasr\data\butt_skin5.paa","","\kt_axmcasr\data\rifle_skin5.paa","\kt_axmcasr\data\rifle_skin5.paa","\kt_axmcasr\data\rifle_skin5.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_grey_bolt2_bcsewpn: kt_axmcasr_grey_bolt2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt2","hu"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_blk.paa","\kt_axmcasr\data\butt_blk.paa","","\kt_axmcasr\data\rifle_blk.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_blk1_bolt2_bcsewpn: kt_axmcasr_blk1_bolt2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt1","hu"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_blk2.paa","\kt_axmcasr\data\butt_blk2.paa","","\kt_axmcasr\data\hu.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_blk2_bolt2_bcsewpn: kt_axmcasr_blk2_bolt2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt1"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_blk2.paa","\kt_axmcasr\data\butt_blk2.paa",""};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle14.rvmat","\kt_axmcasr\data2\butt1.rvmat",""};
	};
	class kt_axmcasr_tan_bolt2_bcsewpn: kt_axmcasr_tan_bolt2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt1","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_tan.paa","\kt_axmcasr\data\butt_tan.paa","","\kt_axmcasr\data\rifle_tan.paa","\kt_axmcasr\data\rifle_tan.paa","\kt_axmcasr\data\rifle_tan.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_skin2_bolt2_bcsewpn: kt_axmcasr_skin2_bolt2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt1","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_skin2.paa","\kt_axmcasr\data\butt_skin2.paa","","\kt_axmcasr\data\rifle_skin2.paa","\kt_axmcasr\data\rifle_skin2.paa","\kt_axmcasr\data\rifle_skin2.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_skin3_bolt2_bcsewpn: kt_axmcasr_skin3_bolt2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt1","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_skin3.paa","\kt_axmcasr\data\butt_skin3.paa","","\kt_axmcasr\data\rifle_skin3.paa","\kt_axmcasr\data\rifle_skin3.paa","\kt_axmcasr\data\rifle_skin3.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_skin4_bolt2_bcsewpn: kt_axmcasr_skin4_bolt2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt1","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_skin4.paa","\kt_axmcasr\data\butt_skin4.paa","","\kt_axmcasr\data\rifle_skin4.paa","\kt_axmcasr\data\rifle_skin4.paa","\kt_axmcasr\data\rifle_skin4.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	class kt_axmcasr_skin5_bolt2_bcsewpn: kt_axmcasr_skin5_bolt2
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","pi","tuo","bolt1","hu","ba","guan"};
		hiddenSelectionsTextures[] = {"","\kt_axmcasr\data\rifle_skin5.paa","\kt_axmcasr\data\butt_skin5.paa","","\kt_axmcasr\data\rifle_skin5.paa","\kt_axmcasr\data\rifle_skin5.paa","\kt_axmcasr\data\rifle_skin5.paa"};
		hiddenSelectionsMaterials[] = {"","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\butt1.rvmat","","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat","\kt_axmcasr\data2\rifle1.rvmat"};
	};
	
	class kt_cslr4;
	class kt_cslr4_2;
	class kt_cslr4_3;
	class kt_cslr4_50;
	class kt_cslr4_50_2;
	class kt_cslr4_338;
	class kt_cslr4_338_2;
	class kt_cslr4_65;
	class kt_cslr4_65_2;
	class kt_qbu203;
	class kt_qbu2032;
	
	class kt_cslr4_bcsewpn:	  kt_cslr4{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_cslr4_2_bcsewpn:	  kt_cslr4_2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_cslr4_3_bcsewpn:	  kt_cslr4_3{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_cslr4_50_bcsewpn:	  kt_cslr4_50{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_cslr4_50_2_bcsewpn:	  kt_cslr4_50_2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_cslr4_338_bcsewpn:	  kt_cslr4_338{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_cslr4_338_2_bcsewpn:	  kt_cslr4_338_2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_cslr4_65_bcsewpn:	  kt_cslr4_65{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_cslr4_65_2_bcsewpn:	  kt_cslr4_65_2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_qbu203_bcsewpn:	  kt_qbu203{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_qbu2032_bcsewpn:	  kt_qbu2032{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	