
	class ar10_mlok01;
	class ar10_mlok01_bcsewpn:	  ar10_mlok01{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_mlok02;
	class ar10_mlok02_bcsewpn:	  ar10_mlok02{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","004","005","006","007","01","02","03","05","12"};
		hiddenSelectionsTextures[] = {"","\kt_ar10\ar102\04.paa","\kt_ar10\ar102\05.paa","\kt_ar10\ar102\06.paa","\kt_ar10\ar102\07.paa","\kt_ar10\ar10\011.paa","\kt_ar10\ar10\021.paa","\kt_ar10\ar102\03.paa","\kt_ar10\ar10\051.paa","\kt_ar10\ar10\121.paa"};
	};
	class ar10_mlok03;
	class ar10_mlok03_bcsewpn:	  ar10_mlok03{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_mlok04;
	class ar10_mlok04_bcsewpn:	  ar10_mlok04{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","001","005","006","007","01","02","03","04","11","13"};
		hiddenSelectionsTextures[] = {"","\kt_ar10\ar10\01.paa","\kt_ar10\ar102\0511.paa","\kt_ar10\ar102\061.paa","\kt_ar10\ar102\071.paa","\kt_ar10\ar102\011.paa","\kt_ar10\ar102\021.paa","\kt_ar10\ar102\031.paa","\kt_ar10\ar102\041.paa","\kt_ar10\ar102\111.paa","\kt_ar10\ar102\131.paa"};
	};
	class ar10_mlok0165;
	class ar10_mlok0165_bcsewpn:	  ar10_mlok0165{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_mlok0265;
	class ar10_mlok0265_bcsewpn:	  ar10_mlok0265{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","004","005","006","007","01","02","03","05","12"};
		hiddenSelectionsTextures[] = {"","\kt_ar10\ar102\04.paa","\kt_ar10\ar102\05.paa","\kt_ar10\ar102\06.paa","\kt_ar10\ar102\07.paa","\kt_ar10\ar10\011.paa","\kt_ar10\ar10\021.paa","\kt_ar10\ar102\03.paa","\kt_ar10\ar10\051.paa","\kt_ar10\ar10\121.paa"};
	};
	class ar10_mlok0365;
	class ar10_mlok0365_bcsewpn:	  ar10_mlok0365{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar10_mlok0465;
	class ar10_mlok0465_bcsewpn:	  ar10_mlok0465{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","001","005","006","007","01","02","03","04","11","13"};
		hiddenSelectionsTextures[] = {"","\kt_ar10\ar10\01.paa","\kt_ar10\ar102\0511.paa","\kt_ar10\ar102\061.paa","\kt_ar10\ar102\071.paa","\kt_ar10\ar102\011.paa","\kt_ar10\ar102\021.paa","\kt_ar10\ar102\031.paa","\kt_ar10\ar102\041.paa","\kt_ar10\ar102\111.paa","\kt_ar10\ar102\131.paa"};
	};
	class kt_M110A1_blk;
	class kt_M110A1_blk_bcsewpn:	  kt_M110A1_blk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","humu1","BarrelGroup","BoltGroup","AddonsGroup","Magazine","Receiver","Stock","VertGrip"};
		hiddenSelectionsTextures[] = {"","\kt_m110a1\data\rail_ar_mk8_13_blk_co.paa","\kt_m110a1\data\Black\BarrelGroup_16_low_CO.paa","\kt_m110a1\data\Black\BoltGroup_low_CO.paa","\kt_m110a1\data\Black\Addons_low_CO.paa","\kt_m110a1\data\Black\Magazine_low_CO.paa","\kt_m110a1\data\Black\Receiver_low_CO.paa","\kt_m110a1\data\Black\Stock_low_CO.paa","\kt_m110a1\data\Black\VerticalGrip_low_CO.paa"};

	};
	class kt_M110A1_ral;
	class kt_M110A1_ral_bcsewpn:	 kt_M110A1_ral{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","humu1","BarrelGroup","BoltGroup","AddonsGroup","Magazine","Receiver","Stock","VertGrip"};
		hiddenSelectionsTextures[] = {"","\kt_m110a1\data\rail_ar_mk8_13_ral.paa","\kt_m110a1\data\RAL8000\BarrelGroup_16_low_CO.paa","\kt_m110a1\data\RAL8000\BoltGroup_low_CO.paa","\kt_m110a1\data\RAL8000\Addons_low_CO.paa","\kt_m110a1\data\RAL8000\Magazine_low_CO.paa","\kt_m110a1\data\RAL8000\Receiver_low_CO.paa","\kt_m110a1\data\RAL8000\Stock_low_CO.paa","\kt_m110a1\data\RAL8000\VerticalGrip_low_CO.paa"};
	};
	class kt_M110A1_fde;
	class kt_M110A1_fde_bcsewpn:	kt_M110A1_fde{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","humu1","BarrelGroup","BoltGroup","AddonsGroup","Magazine","Receiver","Stock","VertGrip"};
		hiddenSelectionsTextures[] = {"","\kt_m110a1\data\rail_ar_mk8_13_DE.paa","\kt_m110a1\data\RAL8000\BarrelGroup_16_low_CO.paa","\kt_m110a1\data\RAL8000\BoltGroup_low_CO.paa","\kt_m110a1\data\RAL8000\Addons_low_CO.paa","\kt_m110a1\data\RAL8000\Magazine_low_CO.paa","\kt_m110a1\data\DarkEarth\Receiver_low_CO.paa","\kt_m110a1\data\RAL8000\Stock_low_CO.paa","\kt_m110a1\data\RAL8000\VerticalGrip_low_CO.paa"};
	};
	class kt_M110A1_blk2;
	class kt_M110A1_blk2_bcsewpn:	  kt_M110A1_blk2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","humu2","BarrelGroup","BoltGroup","AddonsGroup","Magazine","Receiver","Stock","VertGrip","yuan"};
		hiddenSelectionsTextures[] = {"","\kt_m110a1\data\rail_ar_mk8_13_blk41.paa","\kt_m110a1\data\Black\BarrelGroup_16_low_CO.paa","\kt_m110a1\data\Black\BoltGroup_low_CO.paa","\kt_m110a1\data\Black\Addons_low_CO.paa","\kt_m110a1\data\Black\Magazine_low_CO.paa","\kt_m110a1\data\Black\Receiver_low_CO.paa","\kt_m110a1\data\Black\Stock_low_CO.paa","\kt_m110a1\data\Black\VerticalGrip_low_CO.paa","\kt_m110a1\data\hu_blk.paa"};
	};
	class kt_M110A1_ral2;
	class kt_M110A1_ral2_bcsewpn:	  kt_M110A1_ral2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","humu2","BarrelGroup","BoltGroup","AddonsGroup","Magazine","Receiver","Stock","VertGrip","yuan"};
		hiddenSelectionsTextures[] = {"","\kt_m110a1\data\rail_ar_mk8_13_ral21.paa","\kt_m110a1\data\RAL8000\BarrelGroup_16_low_CO.paa","\kt_m110a1\data\RAL8000\BoltGroup_low_CO.paa","\kt_m110a1\data\RAL8000\Addons_low_CO.paa","\kt_m110a1\data\RAL8000\Magazine_low_CO.paa","\kt_m110a1\data\RAL8000\Receiver_low_CO.paa","\kt_m110a1\data\RAL8000\Stock_low_CO.paa","\kt_m110a1\data\RAL8000\VerticalGrip_low_CO.paa","\kt_m110a1\data\hu_ral.paa"};

	};
	class kt_M110A1_fde2;
	class kt_M110A1_fde2_bcsewpn:	  kt_M110A1_fde2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","humu2","BarrelGroup","BoltGroup","AddonsGroup","Magazine","Receiver","Stock","VertGrip","yuan"};
		hiddenSelectionsTextures[] = {"","\kt_m110a1\data\rail_ar_mk8_13_DE21.paa","\kt_m110a1\data\RAL8000\BarrelGroup_16_low_CO.paa","\kt_m110a1\data\RAL8000\BoltGroup_low_CO.paa","\kt_m110a1\data\RAL8000\Addons_low_CO.paa","\kt_m110a1\data\RAL8000\Magazine_low_CO.paa","\kt_m110a1\data\DarkEarth\Receiver_low_CO.paa","\kt_m110a1\data\RAL8000\Stock_low_CO.paa","\kt_m110a1\data\RAL8000\VerticalGrip_low_CO.paa","\kt_m110a1\data\hu_de.paa"};

	};
	class kt_M110A1_blk3;
	class kt_M110A1_blk3_bcsewpn:	 kt_M110A1_blk3{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","humu2","BarrelGroup","BoltGroup","AddonsGroup","Magazine","Receiver","Stock","VertGrip","yuan"};
		hiddenSelectionsTextures[] = {"","\kt_m110a1\data\rail_ar_mk8_13_blk41.paa","\kt_m110a1\data\Black\BarrelGroup_16_low_CO.paa","\kt_m110a1\data\Black\BoltGroup_low_CO.paa","\kt_m110a1\data\Black\Addons_low_CO.paa","\kt_m110a1\data\Black\Magazine_low_CO.paa","\kt_m110a1\data\Black\Receiver_low_CO.paa","\kt_m110a1\data\Black\Stock_low_CO.paa","\kt_m110a1\data\Black\VerticalGrip_low_CO.paa","\kt_m110a1\data\hu_blk.paa"};

	};
	class kt_M110A1_ral3;
	class kt_M110A1_ral3_bcsewpn:	  kt_M110A1_ral3{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","humu2","BarrelGroup","BoltGroup","AddonsGroup","Magazine","Receiver","Stock","VertGrip","yuan"};
		hiddenSelectionsTextures[] = {"","\kt_m110a1\data\rail_ar_mk8_13_ral21.paa","\kt_m110a1\data\RAL8000\BarrelGroup_16_low_CO.paa","\kt_m110a1\data\RAL8000\BoltGroup_low_CO.paa","\kt_m110a1\data\RAL8000\Addons_low_CO.paa","\kt_m110a1\data\RAL8000\Magazine_low_CO.paa","\kt_m110a1\data\RAL8000\Receiver_low_CO.paa","\kt_m110a1\data\RAL8000\Stock_low_CO.paa","\kt_m110a1\data\RAL8000\VerticalGrip_low_CO.paa","\kt_m110a1\data\hu_ral.paa"};

	};
	class kt_M110A1_fde3;
	class kt_M110A1_fde3_bcsewpn:	  kt_M110A1_fde3{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","humu2","BarrelGroup","BoltGroup","AddonsGroup","Magazine","Receiver","Stock","VertGrip","yuan"};
		hiddenSelectionsTextures[] = {"","\kt_m110a1\data\rail_ar_mk8_13_DE21.paa","\kt_m110a1\data\RAL8000\BarrelGroup_16_low_CO.paa","\kt_m110a1\data\RAL8000\BoltGroup_low_CO.paa","\kt_m110a1\data\RAL8000\Addons_low_CO.paa","\kt_m110a1\data\RAL8000\Magazine_low_CO.paa","\kt_m110a1\data\DarkEarth\Receiver_low_CO.paa","\kt_m110a1\data\RAL8000\Stock_low_CO.paa","\kt_m110a1\data\RAL8000\VerticalGrip_low_CO.paa","\kt_m110a1\data\hu_de.paa"};

	};
	class kt_tac5021;
	class kt_tac5021_bcsewpn:	  kt_tac5021{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo_acc","camo_body","boltb"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\data\acc_black_co.paa","\kt_tac50\data\body_black_co.paa",""};
	};
	class kt_tac5022;
	class kt_tac5022_bcsewpn:	  kt_tac5022{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo_acc","camo_body","boltb"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\data\acc_tan_co.paa","\kt_tac50\data\body_tan_co.paa",""};
	};
	class kt_tac5023;
	class kt_tac5023_bcsewpn:	  kt_tac5023{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo_acc","camo_body","boltb"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\data\acc_co.paa","\kt_tac50\data\body_co.paa",""};
	};
	class kt_tac5021_bolt2;
	class kt_tac5021_bolt2_bcsewpn:	  kt_tac5021_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo_acc","camo_body","bolta"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\data\acc_black_co.paa","\kt_tac50\data\body_black_co.paa",""};
	};
	class kt_tac5022_bolt2;
	class kt_tac5022_bolt2_bcsewpn:	  kt_tac5022_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo_acc","camo_body","bolta"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\data\acc_tan_co.paa","\kt_tac50\data\body_tan_co.paa",""};
	};
	class kt_tac5023_bolt2;
	class kt_tac5023_bolt2_bcsewpn:	  kt_tac5023_bolt2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo_acc","camo_body","bolta"};
		hiddenSelectionsTextures[] = {"","\kt_tac50\data\acc_co.paa","\kt_tac50\data\body_co.paa",""};
	};
	class ar15_urgi_cqc_blk;
	class ar15_urgi_cqc_blk_bcsewpn: ar15_urgi_cqc_blk
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto: Noob_Auto{};
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","all"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\urgi\one_02.paa"};
	};
	class ar15_urgi_cqc_blk_grip_bcsewpn: ar15_urgi_cqc_blk_bcsewpn{};
	class ar15_urgi_cqc_blk_grip2_bcsewpn: ar15_urgi_cqc_blk_bcsewpn{};
	class ar15_urgi_cqc_blk_grip3_bcsewpn: ar15_urgi_cqc_blk_bcsewpn{};
	class ar15_urgi_ctr_blk;
	class ar15_urgi_ctr_blk_bcsewpn: ar15_urgi_ctr_blk
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto: Noob_Auto{};
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","urgictr","ctr"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\urgi\one_02.paa","\kt_ar15\data2\ctr\ctr_blk.paa"};
	};
	class ar15_urgi_ctr_blk_grip_bcsewpn: ar15_urgi_ctr_blk_bcsewpn{};
	class ar15_urgi_ctr_blk_grip2_bcsewpn: ar15_urgi_ctr_blk_bcsewpn{};
	class ar15_urgi_ctr_blk_grip3_bcsewpn: ar15_urgi_ctr_blk_bcsewpn{};
	class ar15_urgi_std_blk;
	class ar15_urgi_std_blk_bcsewpn: ar15_urgi_std_blk
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto: Noob_Auto{};
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","all"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\urgi\one_02.paa"};
	};
	class ar15_urgi_std_blk_grip_bcsewpn: ar15_urgi_std_blk_bcsewpn{};
	class ar15_urgi_std_blk_grip2_bcsewpn: ar15_urgi_std_blk_bcsewpn{};
	class ar15_urgi_std_blk_grip3_bcsewpn: ar15_urgi_std_blk_bcsewpn{};
	class ar15_urgi_lb_blk;
	class ar15_urgi_lb_blk_bcsewpn: ar15_urgi_lb_blk
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto: Noob_Auto{};
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","all"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\urgi\one_02.paa"};
	};
	class ar15_urgi_lb_blk_grip_bcsewpn: ar15_urgi_lb_blk_bcsewpn{};
	class ar15_urgi_lb_blk_grip2_bcsewpn: ar15_urgi_lb_blk_bcsewpn{};
	class ar15_urgi_lb_blk_grip3_bcsewpn: ar15_urgi_lb_blk_bcsewpn{};
	class ar15_urgi_cqc_blkgl;
	class ar15_urgi_cqc_blkgl_bcsewpn:	  ar15_urgi_cqc_blkgl{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","all","glacc","gl01"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\urgi\one_02.paa","\kt_ar15\data2\urgi\acc_co_black.paa","\kt_ar15\data2\urgi\eglm_co_black.paa"};
	};
	class ar15_urgi_ctrshot;
	class ar15_urgi_ctrshot_bcsewpn:	  ar15_urgi_ctrshot{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","glall","urgigl2"};
		hiddenSelectionsTextures[] = {"","",""};
	};
	class ar15_urgi_ctrblkshot;
	class ar15_urgi_ctrblkshot_bcsewpn:	  ar15_urgi_ctrblkshot{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","urgictr","ctr","13b","camo3","glall","urgigl2"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\urgi\one_02.paa","\kt_ar15\data2\ctr\ctr_blk.paa","\kt_ar15\data3\13b2.paa","a3\Weapons_F_Enoch\Rifles\MSBS\Data\MSBS_03_black_CO.paa","",""};

	};
	class ar15_urgi_ctr02shot;
	class ar15_urgi_ctr02shot_bcsewpn:	  ar15_urgi_ctr02shot{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","13b","glall"};
		hiddenSelectionsTextures[] = {"","",""};
	};
	class ar15_urgi_cqcshot;
	class ar15_urgi_cqcshot_bcsewpn:	  ar15_urgi_cqcshot{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ar15_urgi_cqcblkshot;
	class ar15_urgi_cqcblkshot_bcsewpn:	  ar15_urgi_cqcblkshot{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","all","camo3"};
		hiddenSelectionsTextures[] = {"","\kt_ar15\data2\urgi\one_02.paa","a3\Weapons_F_Enoch\Rifles\MSBS\Data\MSBS_03_black_CO.paa"};

	};
	class kt_M590_5RD;
	class kt_M590_5RD_bcsewpn:	  kt_M590_5RD{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_M590_8RD;
	class kt_M590_8RD_bcsewpn:	 kt_M590_8RD{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_M1014;
	class kt_M1014_bcsewpn:	 kt_M1014{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_M10142;
	class kt_M10142_bcsewpn:	 kt_M10142{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mcx;
	class kt_mcx_bcsewpn: kt_mcx
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto: Noob_Auto{};
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mcx_grip_bcsewpn: kt_mcx_bcsewpn{};
	class kt_mcx_grip2_bcsewpn: kt_mcx_bcsewpn{};
	class kt_mcx_grip3_bcsewpn: kt_mcx_bcsewpn{};
	class kt_mcx_300blk;
	class kt_mcx_300blk_bcsewpn: kt_mcx_300blk
	{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto: Noob_Auto{};
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_mcx_300blk_grip_bcsewpn: kt_mcx_300blk_bcsewpn{};
	class kt_mcx_300blk_grip2_bcsewpn: kt_mcx_300blk_bcsewpn{};
	class kt_mcx_300blk_grip3_bcsewpn: kt_mcx_300blk_bcsewpn{};
	class kt_QBU10;
	class kt_QBU10_bcsewpn:	  kt_QBU10{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_qbu2033;
	class kt_qbu2033_bcsewpn:	  kt_qbu2033{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_svd1;
	class kt_svd1_bcsewpn:	  kt_svd1{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_svd1_762;
	class kt_svd1_762_bcsewpn:	  kt_svd1_762{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_svd2;
	class kt_svd2_bcsewpn:	  kt_svd2{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class kt_svd2_762;
	class kt_svd2_762_bcsewpn:	  kt_svd2_762{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ktgm_svd;
	class ktgm_svd_bcsewpn:	  ktgm_svd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ktsvd_polymer;
	class ktsvd_polymer_bcsewpn:	  ktsvd_polymer{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class ktsvd_polymer_npz;
	class ktsvd_polymer_npz_bcsewpn:	 ktsvd_polymer_npz{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};



	class VTN_9A91;
	class VTN_9A91_bcsewpn:	  VTN_9A91{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class VTN_9A91_TUNED;
	class VTN_9A91_TUNED_bcsewpn:	  VTN_9A91_TUNED{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class VTN_VSK94;
	class VTN_VSK94_bcsewpn:	  VTN_VSK94{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class VTN_VSK94_TUNED;
	class VTN_VSK94_TUNED_bcsewpn:	  VTN_VSK94_TUNED{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class TS_M240L;
	class TS_M240L_bcsewpn:	  TS_M240L{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		class Noob_Auto:Noob_Auto{};		
		modes[] = {"Noob_Auto"};
		class NGL: NGL{};
		muzzles[] = {"this","NGL"};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
